spring: 
  application: 
    name: PROGRAMA-SERVICE 
 
server: 
  port: 6061 
 
eureka: 
  client: 
    service-url: 
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance: 
    prefer-ip-address: true